version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    container_name: docker-zookeeper
    restart: always
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    container_name: docker-kafka
    environment:
      KAFKA_CREATE_TOPICS: "nome_do_topico:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    restart: always
    logging:
      driver: none
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    hostname: redis
    container_name: docker-redis
    restart: always
    logging:
      driver: none
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    hostname: sqlserver
    container_name: docker-sqlserver
    environment:
      SA_PASSWORD: "Sa123456"
      ACCEPT_EULA: "Y"
    restart: always
    logging:
      driver: none
